export const CREATE_STEP = "CREATE_STEP";
export const DELETE_STEP = "DELETE_STEP";

export const UPDATE_STEP_COUNT = "UPDATE_STEP_COUNT";
export const UPDATE_STEP_SPEED = "UPDATE_STEP_SPEED";
export const UPDATE_STEP_TIME = "UPDATE_STEP_TIME";
export const UPDATE_STEP_NAME = "UPDATE_STEP_NAME";

export const CREATE_STEP_INPUT = "CREATE_STEP_INPUT";
export const UPDATE_STEP_INPUT_COUNT = "UPDATE_STEP_INPUT_COUNT";
export const UPDATE_STEP_INPUT_RESOURCE = "UPDATE_STEP_INPUT_RESOURCE";
export const DELETE_STEP_INPUT = "DELETE_STEP_INPUT";

export const CREATE_STEP_OUTPUT = "CREATE_STEP_OUTPUT";
export const UPDATE_STEP_OUTPUT_COUNT = "UPDATE_STEP_OUTPUT_COUNT";
export const UPDATE_STEP_OUTPUT_RESOURCE = "UPDATE_STEP_OUTPUT_RESOURCE";
export const DELETE_STEP_OUTPUT = "DELETE_STEP_OUTPUT";

export const START_CANCEL_OUT = "START_CANCEL_OUT";
export const FINALIZE_CANCEL_OUT = "FINALIZE_CANCEL_OUT";
export const CANCEL_CANCEL_OUT = "CANCEL_CANCEL_OUT";

export const IMPORT_STEPS = "IMPORT_STEPS";

export const SCALE_SYSTEM = "SCALE_SYSTEM";
