export const CREATE_STEP = 'CREATE_STEP';
export const DELETE_STEP = 'DELETE_STEP';

export const UPDATE_STEP_TIME = 'UPDATE_STEP_TIME';
export const UPDATE_STEP_NAME = 'UPDATE_STEP_NAME';
export const TOGGLE_STEP_MINIMIZED = 'TOGGLE_STEP_MINIMIZED';

export const CREATE_STEP_INPUT = 'CREATE_STEP_INPUT';
export const UPDATE_STEP_INPUT_COUNT = 'UPDATE_STEP_INPUT_COUNT';
export const UPDATE_STEP_INPUT_RESOURCE = 'UPDATE_STEP_INPUT_RESOURCE';
export const DELETE_STEP_INPUT = 'DELETE_STEP_INPUT';

export const CREATE_STEP_OUTPUT = 'CREATE_STEP_OUTPUT';
export const UPDATE_STEP_OUTPUT_COUNT = 'UPDATE_STEP_OUTPUT_COUNT';
export const UPDATE_STEP_OUTPUT_RESOURCE = 'UPDATE_STEP_OUTPUT_RESOURCE';
export const DELETE_STEP_OUTPUT = 'DELETE_STEP_OUTPUT';

export const ADD_RESOURCE_COUNT = 'ADD_RESOURCE_COUNT';
export const DELETE_RESOURCE_COUNT = 'DELETE_RESOURCE_COUNT';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const UPDATE_COUNT = 'UPDATE_COUNT';

export const SET_EXTRA_OUTPUT = 'SET_EXTRA_OUTPUT';
export const SET_ACTUAL_INPUT = 'SET_ACTUAL_INPUT';